# 使用说明 V3.2.0
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '2'
services:
  pigx-mysql:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: pigx-mysql
    image: pigx-mysql
    ports:
      - 3306:3306
    volumes:
      - ./pigx-mysql:/var/lib/mysql
    command: --lower_case_table_names=1

  pigx-zookeeper:
    image: zookeeper:3.4.13
    restart: always

  pigx-redis:
    image: redis:5.0.4
    restart: always
    container_name: pigx-redis
    ports:
      - 6379:6379

  pigx-minio:
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    environment:
      - MINIO_DOMAIN=pigx-minio
      - MINIO_ACCESS_KEY=lengleng
      - MINIO_SECRET_KEY=lengleng

  pigx-register:
    build:
      context: ./
      dockerfile: ./pigx-register/Dockerfile
    restart: always
    container_name: pigx-register
    image: pigx-register
    ports:
      - 8848:8848

  pigx-gateway:
    build:
      context: ./
      dockerfile: ./pigx-gateway/Dockerfile
    restart: always
    container_name: pigx-gateway
    image: pigx-gateway
    ports:
      - 9999:9999

  pigx-auth:
    build:
      context: ./
      dockerfile: ./pigx-auth/Dockerfile
    restart: always
    container_name: pigx-auth
    image: pigx-auth

  pigx-upms:
    build:
      context: ./
      dockerfile: ./pigx-upms/pigx-upms-biz/Dockerfile
    restart: always
    container_name: pigx-upms
    image: pigx-upms

  pigx-monitor:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-monitor/Dockerfile
    restart: always
    image: pigx-monitor
    container_name: pigx-monitor
    ports:
      - 5001:5001

  pigx-daemon-quartz:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-daemon-quartz/Dockerfile
    restart: always
    image: pigx-daemon-quartz
    container_name: pigx-daemon-quartz

  pigx-daemon-elastic-job:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-daemon-elastic-job/Dockerfile
    restart: always
    image: pigx-daemon-elastic-job
    container_name: pigx-daemon-elastic-job

  pigx-codegen:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-codegen/Dockerfile
    restart: always
    image: pigx-codegen
    container_name: pigx-codegen

  pigx-mp-manager:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-mp-manager/Dockerfile
    restart: always
    image: pigx-mp-manager
    container_name: pigx-mp-manager

  pigx-pay:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-pay/Dockerfile
    restart: always
    image: pigx-pay
    container_name: pigx-pay

  pigx-activiti:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-activiti/Dockerfile
    restart: always
    image: pigx-activiti
    container_name: pigx-activiti

  pigx-tx-manager:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-tx-manager/Dockerfile
    restart: always
    image: pigx-tx-manager
    container_name: pigx-tx-manager
    ports:
      - 5004:5004
      - 9998:9998
